### ISSUE TITLE
Rubocop-minitest 0.6.1 errors on assert(variable)

### ISSUE THREAD

**Issue by herwinw** [rubocop-hq/rubocop-minitest#55]
Minimal reproduction case:
```ruby
a = true
assert(a)
```

--------

## Expected behavior

Accept this code

## Actual behavior

```
An error occurred while Minitest/AssertIncludes cop was inspecting $filename.
undefined method `method?' for s(:lvar, :a):RuboCop::AST::Node
Did you mean?  method
               methods
.../rubocop-minitest-0.6.1/lib/rubocop/cop/mixin/includes_cop_rule.rb:16:in `on_send'
.......
```

## Steps to reproduce the problem

See above

## RuboCop version
```
$ [bundle exec] rubocop -V
0.80.0 (using Parser 2.7.0.2, running on ruby 2.3.3 i386-linux-gnu)
```

**Comment by rmm5t** [comment]
I just experienced the exact same issue after upgrading to v0.6.1

**Comment by koic** [comment]
RuboCop Minitest 0.6.2 has been released to solve this issue. Thanks for your feedback.
